### PR TITLE
App dockerised

### PR DESCRIPTION
**Pull request by spaul91**
Will not use bare uploader install, because it's difficult to get working. Using a docker image is easier.

Other changes include some behaviour of the runtime script:

- samplesheet name coercion
- case metadata autogeneration
- running the container and launching executions

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/1)

### CODE REVIEW

**Review by PolarisAstrum-NHS — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/1)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @spaul91)

___
*[`src/script.sh` line 54 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/1#-OAXrE_V77xAZpu1aMIX:-OAXrE_V77xAZpu1aMIY:bykh0v9) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/3416268a3c2a39b319d7c6c50dd87d081c2991b4/src/script.sh#L54)):*
> ```Shell
> 
> main() {
>     dx-download-all-inputs
> ```

Why is this line here if you have commented below that that you can't use it?

**Comment by spaul91** [comment]
*[`src/script.sh` line 54 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/1#-OAXrE_V77xAZpu1aMIX:-OAXvD7t9JBix2WhCC5v:bbx5znj) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/3416268a3c2a39b319d7c6c50dd87d081c2991b4/src/script.sh#L54)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Why is this line here if you have commented below that that you can't use it?
</blockquote></details>

As discussed on Slack, I do this to download all of the inputs that aren't the run folder, or I'd have to download them all individually. I'll add a comment to clarify this

**Review by PolarisAstrum-NHS — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spaul91)

**Review by PolarisAstrum-NHS — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/1#-:-OAXwJB8E0gatMv--BmI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spaul91)

**Pull request merged**
