### PR TITLE
Various improvements

### LINKED ISSUE #2: Enhancement for sample sheet matching
Case insensitive matching for sample sheet, this would deal with scenarios where SampleSheet.csv is named incorrectly as sampleSheet.csv or samplesheet.csv.

https://github.com/eastgenomics/eggd_ici_uploader/blob/83b77d03c2775f02e892112382ef048f17b6da09/src/script.sh#L64

### PR DESCRIPTION
**Pull request by spaul91**
- `-irunfolder` option supports entering project of source run
    - will search job project if project not provided
- "dry run" testing mode added
- various bugfixes

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/3)

### CODE REVIEW

**Review by PolarisAstrum-NHS — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/3)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @spaul91)

___
*[`src/script.sh` line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/3#-OB0Sn2u7Wb6JjlULop9:-OB0Sn2u7Wb6JjlULopA:b-hea8lk) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/da1932fbaddb944eac366acc52dfeba6a949595d/src/script.sh#L11)):*
> ```Shell
>     OUT_FOLDER=$2
> 
>     if grep -eq "^project-" <<< $RUN_PATH; then
> ```

Could you explain the logic behind this check please? It's a little difficult to work out from just the code

**Comment by spaul91** [comment]
*[`src/script.sh` line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/3#-OB0Sn2u7Wb6JjlULop9:-OB0U8o26mBIuLvbFp6K:b-81f0h2) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/da1932fbaddb944eac366acc52dfeba6a949595d/src/script.sh#L11)):*
<details><summary><i>Previously, PolarisAstrum-NHS (Polaris Astrum) wrote…</i></summary><blockquote>

Could you explain the logic behind this check please? It's a little difficult to work out from just the code
</blockquote></details>

Sure :) if you enter a run name like "project-12345:/path/to/folder" the app will look in that project for your folder, regardless of where your job runs. If you enter just "/path/to/folder" it'll look in the project your job was launched in. I added this feature because running the app was a pain if you weren't precisely in the project your run data is stored.

**Review by PolarisAstrum-NHS — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/3)* status: 5 of 6 files reviewed, all discussions resolved

___
*[`src/script.sh` line 11 at r1](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/3#-OB0Sn2u7Wb6JjlULop9:-OB0VAUL4zPlU4ALns-2:b5s6tz0) ([raw file](https://github.com/eastgenomics/eggd_ici_uploader/blob/da1932fbaddb944eac366acc52dfeba6a949595d/src/script.sh#L11)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Sure :) if you enter a run name like "project-12345:/path/to/folder" the app will look in that project for your folder, regardless of where your job runs. If you enter just "/path/to/folder" it'll look in the project your job was launched in. I added this feature because running the app was a pain if you weren't precisely in the project your run data is stored.
</blockquote></details>

Thanks, that makes sense

**Review by PolarisAstrum-NHS — APPROVED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_ici_uploader/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spaul91)

**Pull request merged**
